// Generated by CoffeeScript 1.4.0
(function() {
  var foursquare, params;

  require('coffee-script');

  foursquare = (require('./foursquarevenues'))("CLIENT_ID", "CLIENT_SECRET");

  params = {
    "ll": "40.7,-74"
  };

  foursquare.getVenues(params, function(error, venues) {
    if (!error) {
      return console.log(venues);
    }
  });

  foursquare.exploreVenues(params, function(error, venues) {
    if (!error) {
      return console.log(venues);
    }
  });

}).call(this);
