// Generated by CoffeeScript 1.3.3
(function() {
  var request;

  require('coffee-script');

  request = require('request');

  module.exports = function(client_id, client_secret) {
    return {
      getVenues: function(params) {
        var date, day, month, today, urlString;
        urlString = "https://api.foursquare.com/v2/venues/search?";
        if (params.ll != null) {
          urlString += "&ll=" + params.ll;
        }
        if (params.near != null) {
          urlString += "&near=" + params.near;
        }
        if (params.llAcc != null) {
          urlString += "&llAcc=" + params.llAcc;
        }
        if (params.alt != null) {
          urlString += "&alt=" + params.alt;
        }
        if (params.altAcc != null) {
          urlString += "&altAcc=" + params.altAcc;
        }
        if (params.query != null) {
          urlString += "&ll=query" + params.query;
        }
        if (params.limit != null) {
          urlString += "&limit=" + params.limit;
        }
        if (params.intent != null) {
          urlString += "&intent=" + params.intent;
        }
        if (params.radius != null) {
          urlString += "&radius=" + params.radius;
        }
        if (params.sw != null) {
          urlString += "&sw=" + params.sw;
        }
        if (params.ne != null) {
          urlString += "&ne=" + params.ne;
        }
        if (params.categoryId != null) {
          urlString += "&categoryId=" + params.categoryId;
        }
        if (params.url != null) {
          urlString += "&url=" + params.url;
        }
        if (params.providerId != null) {
          urlString += "&providerId=" + params.prodividerId;
        }
        if (params.linkedId != null) {
          urlString += "&linkedId=" + params.linkedId;
        }
        if (client_id != null) {
          urlString += "&client_id=" + client_id;
        }
        if (client_secret != null) {
          urlString += "&client_secret=" + client_secret;
        }
        today = new Date();
        month = today.getMonth() + 1;
        if (month < 10) {
          month = "0" + month;
        }
        day = today.getDate();
        if (day < 10) {
          day = "0" + day;
        }
        date = today.getFullYear() + month + day;
        urlString += "&v=" + date;
        return request(urlString, function(error, response, body) {
          if (!error && response.statusCode === 200) {
            return JSON.parse(body);
          }
        });
      }
    };
  };

}).call(this);
